[project]
name = "uv-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.116.1",
    "jwt>=1.4.0",
    "passlib>=1.7.4",
    "prisma>=0.15.0",
    "redis>=6.2.0",
    "uvicorn>=0.35.0",
]
